# springboot基本配置
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: 123456
#    virtual-host: /
#logging:
#  level:
#    com.example.rabbitmq.springboot.consumer: info
#    root: info

# queue增加队列确认配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
logging:
  level:
    com.example.rabbitmq.springboot.consumer: info
    root: info