server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: mall-auth
security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234
      registered-redirect-uri: http://mrbird.cc
